# Zizmor security scanner configuration
# See: https://docs.zizmor.sh/configuration/
#
# Pre-commit uses: --persona=regular --min-severity=medium --min-confidence=medium
# This catches high-signal security issues while reducing noise.
#
# To run a full audit: zizmor --persona=auditor .github/workflows/

rules:
  # IGNORED: Requires pinning all actions to SHA hashes
  # TODO: Create a separate PR to pin all actions to commit SHAs
  # This is a significant change requiring updates across all workflows
  unpinned-uses:
    ignore:
      - _claude-settings.yml
      - _nix-build.yml
      - ai-openhands.yml
      - auto-merge.yml
      - best-practices.yml
      - ci-auto-claude.yml
      - ci-eol-check.yml
      - ci-fail-issue.yml
      - ci-file-length.yml
      - ci-fix.yml
      - ci-gate.yml
      - ci-markdownlint.yml
      - ci-nix.yml
      - ci-package-staleness.yml
      - ci-validate-settings.yml
      - ci-validate.yml
      - claude-review.yml
      - code-simplifier.yml
      - copilot-setup-steps.yml
      - deps-monitor-packages.yml
      - deps-update-flake.yml
      - final-pr-review.yml
      - issue-hygiene.yml
      - issue-sweeper.yml
      - issue-auto-resolve.yml
      - issue-pipeline.yml
      - next-steps.yml
      - nixos-release-check.yml
      - post-merge-docs-review.yml
      - post-merge-tests.yml
      - review-deps.yml

  # ACCEPTED: workflow_run is the only trigger for reacting to CI completions.
  # ci-fix.yml and ci-fail-issue.yml are safe because:
  # - They only read logs via the GitHub API (not fork PR code).
  # - They do not execute untrusted fork code.
  # - ci-fix.yml: the should-fix job validates the PR exists and belongs to this repo.
  # - ci-fail-issue.yml: only triggers on main branch CI Gate failures.
  dangerous-triggers:
    ignore:
      - ci-fail-issue.yml
      - ci-fix.yml

  # ACCEPTED: secrets: inherit is required for reusable workflow callers.
  # These thin callers delegate to JacobPEvans/ai-workflows reusable workflows
  # which need CLAUDE_CODE_OAUTH_TOKEN and other repo secrets at runtime.
  # The reusable workflows are owned by the same org and are trusted.
  secrets-inherit:
    ignore:
      - best-practices.yml
      - ci-fail-issue.yml
      - ci-fix.yml
      - claude-review.yml
      - code-simplifier.yml
      - final-pr-review.yml
      - issue-hygiene.yml
      - issue-sweeper.yml
      - issue-auto-resolve.yml
      - issue-pipeline.yml
      - next-steps.yml
      - post-merge-docs-review.yml
      - post-merge-tests.yml

  # ACCEPTED: Workflow-level write permissions are required for cross-repo
  # reusable workflow calls. permissions: {} causes startup_failure because
  # reusable workflows need the caller to provide sufficient GITHUB_TOKEN scope.
  #
  # post-merge-docs-review.yml and post-merge-tests.yml use the dispatch pattern:
  # a 'dispatch' job (needs actions: write) re-triggers the workflow on push, then
  # a 'review' job (needs contents/id-token/pull-requests: write) calls the reusable
  # workflow. GitHub requires workflow-level to hold the union of all job needs.
  # The dispatch job explicitly restricts its own access via job-level permissions.
  excessive-permissions:
    ignore:
      - issue-auto-resolve.yml
      - issue-pipeline.yml
      - post-merge-docs-review.yml
      - post-merge-tests.yml

  # IGNORED: Low-confidence credential persistence warnings
  # Most checkouts don't need persist-credentials: false unless
  # the workflow later runs untrusted code with git access
  artipacked:
    ignore:
      - _claude-settings.yml
      - _nix-build.yml
      - ai-openhands.yml
      - ci-auto-claude.yml
      - ci-eol-check.yml
      - ci-file-length.yml
      - ci-gate.yml
      - ci-markdownlint.yml
      - ci-nix.yml
      - ci-package-staleness.yml
      - ci-validate-settings.yml
      - ci-validate.yml
      - deps-monitor-packages.yml
      - deps-update-flake.yml
      - nixos-release-check.yml
      - review-deps.yml
