# Agent OS Home-Manager Module
#
# A proper home-manager module for Agent OS integration.
# Provides spec-driven development workflows for AI coding agents.
#
# Usage:
#   programs.agent-os = {
#     enable = true;
#     claudeCodeCommands = true;
#     useClaudeCodeSubagents = true;
#   };
#
# After rebuild, run ~/agent-os/scripts/project-install.sh in any project
# to compile Agent OS into .claude/commands/agent-os/ and related directories.
#
# Reference: https://buildermethods.com/agent-os

{ config, lib, agent-os, ... }:

let
  cfg = config.programs.agent-os;

  # Generate config.yml using lib.generators.toYAML for robustness
  configYaml = lib.generators.toYAML {} {
    defaults = {
      profile = cfg.profile;
      claude_code_commands = cfg.claudeCodeCommands;
      use_claude_code_subagents = cfg.useClaudeCodeSubagents;
      standards_as_claude_code_skills = cfg.standardsAsClaudeCodeSkills;
      agent_os_commands = cfg.agentOsCommands;
    };
  };

  # Scripts to symlink from the upstream repo
  scripts = [
    "common-functions.sh"
    "create-profile.sh"
    "project-install.sh"
    "project-update.sh"
  ];

  # Generate file entries for each script
  scriptFiles = builtins.listToAttrs (map (name: {
    name = "agent-os/scripts/${name}";
    value = {
      source = "${agent-os}/scripts/${name}";
      executable = true;
    };
  }) scripts);

in {
  options.programs.agent-os = {
    enable = lib.mkEnableOption "Agent OS integration for spec-driven AI development";

    profile = lib.mkOption {
      type = lib.types.str;
      default = "default";
      description = "Agent OS profile to use. Custom profiles can be created with create-profile.sh.";
    };

    claudeCodeCommands = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Install Claude Code slash commands for Agent OS.
        Provides /shape-spec, /write-spec, /create-tasks, /implement-tasks, etc.
      '';
    };

    useClaudeCodeSubagents = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Allow Claude Code commands to delegate tasks to specialized subagents.
        More autonomous but higher token usage. Requires claudeCodeCommands.
      '';
    };

    standardsAsClaudeCodeSkills = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Convert standards to Claude Code Skills in .claude/skills/.
        Claude applies them automatically based on context. Requires claudeCodeCommands.
      '';
    };

    agentOsCommands = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Generate Agent OS commands in agent-os/commands/ for other AI tools.
        Use this for Cursor, Windsurf, Codex, Gemini, etc.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Enforce option dependencies
    assertions = [
      {
        assertion = cfg.useClaudeCodeSubagents -> cfg.claudeCodeCommands;
        message = "programs.agent-os.useClaudeCodeSubagents requires programs.agent-os.claudeCodeCommands to be enabled.";
      }
      {
        assertion = cfg.standardsAsClaudeCodeSkills -> cfg.claudeCodeCommands;
        message = "programs.agent-os.standardsAsClaudeCodeSkills requires programs.agent-os.claudeCodeCommands to be enabled.";
      }
    ];

    home.file = {
      # Nix-generated configuration
      "agent-os/config.yml".text = ''
        # Agent OS Configuration
        # Generated by Nix - do not edit manually
        # To change settings, update programs.agent-os in your Nix configuration
      '' + configYaml;

      # Upstream files
      "agent-os/CHANGELOG.md".source = "${agent-os}/CHANGELOG.md";
      "agent-os/profiles/default".source = "${agent-os}/profiles/default";
    } // scriptFiles;
  };
}
