# SOPS configuration for nix-config
# Age key: ~/.config/sops/age/keys.txt
# Encrypt: sops --encrypt --in-place <file>
# Edit: sops <file>

creation_rules:
  - path_regex: \.sops\.json$
    age: "age1y0jvtlp2ac8fwwvh2nzm88ehye74jlseywjrjcjqll7u8vycsedq788tp9"
  - path_regex: \.sops\.yaml$
    age: "age1y0jvtlp2ac8fwwvh2nzm88ehye74jlseywjrjcjqll7u8vycsedq788tp9"
