# Security Configuration
#
# CRITICAL: This file contains security-sensitive settings.
# Changes here affect system-level permissions and should be reviewed carefully.
#
# Current security policies:
# - Passwordless sudo for darwin-rebuild and system activation (enables AI assistants)

_:

let
  userConfig = import ../../lib/user-config.nix;
in
{
  # ==========================================================================
  # Passwordless sudo for darwin-rebuild and system activation
  # ==========================================================================
  # Purpose: Allow AI assistants (Claude Code, etc.) to run darwin-rebuild switch
  # and system activation without prompting for password.
  #
  # Security considerations:
  # - ONLY darwin-rebuild and activation are allowed passwordless
  # - darwin-rebuild can only modify Nix-managed system configuration
  # - Activation only applies already-built Nix store paths
  # - All changes are declarative and version-controlled in this repo
  # - Rollback is always possible via darwin-rebuild --rollback
  #
  # Implementation: Creates /etc/sudoers.d/darwin-rebuild via environment.etc
  # nix-darwin doesn't have security.sudo.extraRules, so we use etc files
  #
  # To disable: comment out or remove the environment.etc block
  environment.etc."sudoers.d/darwin-rebuild".text = ''
    # Allow ${userConfig.user.name} to run darwin-rebuild and activate without password
    # Generated by nix-darwin - do not edit manually
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /run/current-system/sw/bin/darwin-rebuild
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /nix/var/nix/profiles/system/activate
  '';
}
