# Powerline Theme - Claude Code Statusline
#
# Multi-line statusline with powerline-style graphics powered by claude-powerline.
# Builds the package from source using Nix for reproducible, hermetic deployment.
#
# Features:
# - Multi-line layout (3 lines by default)
# - 5-hour billing block tracking with reset timer
# - Session and daily cost tracking
# - Full directory path display
# - Git info (branch, worktree, SHA, stash count, upstream)
# - Context window usage
# - 6 customizable color themes
#
# Repository: https://github.com/Owloops/claude-powerline
{
  config,
  lib,
  pkgs,
  claude-powerline,
  ...
}:

let
  cfg = config.programs.claudeStatusline;
  powerlineStyle = cfg.powerline.style;

  # Build claude-powerline as a Nix package from the flake input
  # This ensures reproducible builds without runtime network dependencies
  claude-powerline-pkg = pkgs.buildNpmPackage {
    pname = "claude-powerline";
    version = "1.13.2";
    src = claude-powerline;

    # Hash of npm dependencies (verified against package-lock.json)
    # Generated by setting to lib.fakeHash and extracting from build error
    npmDepsHash = "sha256-4xTN96MCAonXjsArM/oWCYnStqidjpQOsy9f4IJleTs=";

    # TypeScript build process (runs tsup to generate dist/)
    npmBuild = "npm run build";

    meta = {
      description = "Beautiful powerline statusline for Claude Code";
      homepage = "https://github.com/Owloops/claude-powerline";
      license = lib.licenses.mit;
      platforms = lib.platforms.all;
      mainProgram = "claude-powerline";
    };
  };

  # Map our style names to claude-powerline theme names
  themeMap = {
    "default" = "dark";
    "minimal" = "dark";
    "rainbow" = "dark";
    "gruvbox" = "gruvbox";
    "dracula" = "dark"; # closest match
    "nord" = "nord";
  };
  themeName = themeMap.${powerlineStyle} or "dark";

  # Rich multi-line configuration for claude-powerline
  # Displays: directory, git (branch, worktree, SHA, stash, upstream), model, session costs, 5-hour block, daily usage, context
  powerlineConfig = {
    theme = themeName;
    style = "powerline";
    charset = "unicode";

    display = {
      lines = [
        # Line 1: Directory (full path), Git info (branch, worktree, SHA, stash, upstream), Model
        {
          segments = {
            directory = {
              enabled = true;
              style = "full"; # Show full path from ~
            };
            git = {
              enabled = true;
              showBranch = true; # Always show current branch
              showWorktree = true; # Show worktree name/path when in a worktree
              showSha = true;
              showStash = true;
              showUpstream = true;
              showRepoName = true; # Show repo name to help identify worktree
            };
            model = {
              enabled = true;
            };
          };
        }
        # Line 2: Session cost, 5-hour block, Daily usage
        {
          segments = {
            session = {
              enabled = true;
              type = "breakdown"; # Show input/output split
            };
            block = {
              enabled = true;
              type = "weighted"; # Account for model multipliers
              burnType = "cost"; # Show burn rate
            };
            today = {
              enabled = true;
              type = "breakdown";
            };
          };
        }
        # Line 3: Context window, Metrics
        {
          segments = {
            context = {
              enabled = true;
            };
            metrics = {
              enabled = true;
            };
            version = {
              enabled = true;
            };
          };
        }
      ];
    };

    # Budget warnings at 80%
    budget = {
      session = {
        amount = 10.0;
        warningThreshold = 80;
      };
      today = {
        amount = 25.0;
        warningThreshold = 80;
      };
      block = {
        amount = 15.0;
        type = "cost";
        warningThreshold = 80;
      };
    };
  };

  # Write config to JSON file
  configFile = pkgs.writeText "claude-powerline.json" (builtins.toJSON powerlineConfig);

in
{
  config = lib.mkIf (cfg.enable && cfg.theme == "powerline") {
    # Use ONLY the script option with actual content
    # settings.nix will:
    #   1. Create ~/.claude/statusline-command.sh with this content
    #   2. Add statusLine to settings.json pointing to that script
    # DO NOT also use home.file - that causes duplicate file creation = fork bomb!
    programs.claude.statusLine = {
      enable = true;
      script = ''
        #!/usr/bin/env bash
        # Claude Powerline statusline wrapper
        # Rich multi-line display with cost tracking
        # Enhanced with worktree detection (Issue #108)

        # Detect and display worktree information
        worktree_info=""
        if command -v git &> /dev/null; then
          # Try to get the git directory path. This command will fail if not in a git repo.
          if git_dir=$(git rev-parse --git-dir 2>/dev/null); then
            # Check if this is a worktree (git-dir contains .git/worktrees/ anywhere in path)
            # This handles both relative (.git/worktrees/name) and absolute (/path/.git/worktrees/name) paths
            if [[ "$git_dir" =~ \.git/worktrees/([^/]+)$ ]]; then
              worktree_name="''${BASH_REMATCH[1]}"
              # Format: [worktree: name]
              worktree_info="[worktree: $worktree_name] "
            fi
          fi
        fi

        # If we have worktree info, display it before the powerline output
        if [[ -n "$worktree_info" ]]; then
          printf '\033[1;36m%s\033[0m\n' "$worktree_info"
        fi

        # Run claude-powerline with config
        ${claude-powerline-pkg}/bin/claude-powerline --config=${configFile} "$@"
      '';
    };
  };
}
