# Powerline Theme - Claude Code Statusline
#
# Multi-line statusline with powerline-style graphics powered by claude-powerline.
# Builds the package from source using Nix for reproducible, hermetic deployment.
#
# Features:
# - Powerline-style arrow separators
# - Multi-line layout
# - Enhanced git status display
# - 6 customizable color themes
#
# Repository: https://github.com/Owloops/claude-powerline
{
  config,
  lib,
  pkgs,
  claude-powerline,
  ...
}:

let
  cfg = config.programs.claudeStatusline;
  powerlineStyle = cfg.powerline.style;

  # Build claude-powerline as a Nix package from the flake input
  # This ensures reproducible builds without runtime network dependencies
  claude-powerline-pkg = pkgs.buildNpmPackage {
    pname = "claude-powerline";
    version = "1.13.2";
    src = claude-powerline;

    # Hash of npm dependencies (verified against package-lock.json)
    # Generated by setting to lib.fakeHash and extracting from build error
    npmDepsHash = "sha256-FZGHvb64NT6e1G9KW0J8Js/YaH+FQ7gXwFxXdUQ6K+s=";

    # TypeScript build process (runs tsup to generate dist/)
    npmBuild = "npm run build";

    meta = with lib; {
      description = "Beautiful powerline statusline for Claude Code";
      homepage = "https://github.com/Owloops/claude-powerline";
      license = licenses.mit;
      platforms = platforms.all;
      mainProgram = "claude-powerline";
    };
  };

  # Build the theme argument for the statusline script
  themeArg = lib.optionalString (powerlineStyle != "default") "--theme=${powerlineStyle}";
in
{
  config = lib.mkIf (cfg.enable && cfg.theme == "powerline") {
    # Create statusline wrapper script that calls the Nix-built package
    home.file.".claude/statusline-command.sh" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # Claude Powerline statusline wrapper
        # Calls the Nix-built claude-powerline package from the store
        ${claude-powerline-pkg}/bin/claude-powerline ${themeArg} "$@"
      '';
    };

    # Bridge configuration: register the statusline script with settings.nix
    # This ensures the script is referenced in ~/.claude/settings.json
    programs.claude.statusLine = {
      enable = true;
      script = "${config.home.homeDirectory}/.claude/statusline-command.sh";
    };
  };
}
